$activeBorderColor = rgb(e0a526)

general {
    col.active_border = rgba(e0a526ee) rgba(5a9ae8ee) rgba(e0a526ee) 45deg
    col.inactive_border = rgba(3a3a48aa)
}

group {
    col.border_active = $activeBorderColor
}

decoration {
    rounding = 12
    dim_inactive = true
    dim_strength = 0.08
    
    blur {
        enabled = true
        size = 6
        passes = 2
        new_optimizations = true
    }
}

animations {
    animation = borderangle, 1, 30, linear, loop
    animation = windows, 1, 5, wind, slide
    animation = windowsOut, 1, 5, default, popin 80%
    animation = border, 1, 5, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 5, default
}
